### ISSUE TITLE
Mixing queued commands with immediate commands

### ISSUE THREAD

**Issue by shadowhand** [php-enqueue/tactician-queue-interop#1]
From what I can tell, this package assumes that **every** command that goes into Tactician should be queued. This cannot work for us, as only some of our commands can be queued and the others must be executed immediately.

For instance, [tactician-bernard provides a middleware](https://github.com/thephpleague/tactician-bernard/blob/master/src/QueueMiddleware.php) that only sends `Bernard\Message` instances to the queue. If enqueue did this, it would be be suitable for our use case.

**Comment by makasim** [comment]
@shadowhand The extension was heavily reworked and now it contains what you need. Could you please take a look at https://github.com/php-enqueue/tactician-queue-interop/pull/2.

Will be released as 0.2.0

**Comment by shadowhand** [comment]
From what I can tell, this is still missing a critical piece:

If the command has been queued, it should not be processed by the producing handler.

**Comment by makasim** [comment]
@shadowhand It shouldn't. Isn't this line is exactly for that purpose https://github.com/php-enqueue/tactician-queue-interop/blob/master/src/QueueMiddleware.php#L50?

**Comment by makasim** [comment]
* QueueMessage - Indicates that the message must be queued to a MQ broker.
* QueuedMessage - Indicates that the message has been sent to a MQ broker.
* ReceivedMessage - Indicates that the message is received from a MQ broker.

**Comment by shadowhand** [comment]
```php
$next(new QueuedMessage($command));
```

Will continue processing the message. If the goal is to abort processing, it should just `return;`

**Comment by shadowhand** [comment]
https://github.com/thephpleague/tactician-bernard/blob/master/src/QueueMiddleware.php#L34-L36

**Comment by makasim** [comment]
Got it. That's easy to fix.
